import { Link, createFileRoute } from "@tanstack/react-router";
import { Bell } from "lucide-react";
import { notifications as notificationsApi } from "@/services/api/notifications";
import { demoNotifications } from "@/services/demo/dataset";
import { usePvQuery } from "@/lib/data-source";
import {
  EmptyState,
  PageHeader,
  QueryBoundary,
  Section,
  SourceTag,
  StatusPill,
  type Tone,
} from "@/components/pv/primitives";
import type { Notification } from "@/types/pv";

export const Route = createFileRoute("/_app/notifications")({
  head: () => ({
    meta: [
      { title: "Notifications — MedNova PV Assist" },
      { name: "description", content: "Case assignments, seriousness flags, overdue follow-ups, coding and review requests." },
      { property: "og:title", content: "Notifications — MedNova PV Assist" },
      { property: "og:description", content: "Operational notification centre for pharmacovigilance teams." },
    ],
  }),
  component: NotificationsPage,
});

const tone: Record<Notification["type"], Tone> = {
  CASE_ASSIGNED: "info",
  SERIOUSNESS_MISMATCH: "warning",
  FOLLOW_UP_DUE: "warning",
  CASE_OVERDUE: "critical",
  CODING_REQUIRED: "info",
  MANAGER_REVIEW: "info",
  SIGNAL_REVIEW: "warning",
  PSUR_COMPLETE: "success",
  LINELIST_FAILED: "critical",
};

function NotificationsPage() {
  const query = usePvQuery(["notifications"], () => notificationsApi.list(), () => demoNotifications);
  return (
    <>
      <PageHeader
        title="Notifications"
        description="Work items generated by the platform. Opening a notification does not change any safety record."
        meta={query.data ? <SourceTag source={query.data.source} /> : null}
      />
      <div className="p-6">
        <Section title="All notifications">
          <QueryBoundary query={query}>
            {(items) =>
              items.length === 0 ? (
                <EmptyState title="Nothing to review" />
              ) : (
                <ul className="divide-y divide-border">
                  {items.map((n) => (
                    <li key={n.id} className="flex flex-wrap items-start gap-3 py-3">
                      <Bell className={n.read ? "mt-0.5 size-4 text-muted-foreground" : "mt-0.5 size-4 text-primary"} />
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <p className="text-sm font-medium">{n.title}</p>
                          <StatusPill tone={tone[n.type]}>{n.type.replaceAll("_", " ").toLowerCase()}</StatusPill>
                          {!n.read ? <StatusPill tone="info">unread</StatusPill> : null}
                        </div>
                        <p className="mt-0.5 text-sm text-muted-foreground">{n.body}</p>
                      </div>
                      <span className="mono-num text-xs text-muted-foreground">
                        {n.at.replace("T", " ").slice(0, 16)} UTC
                      </span>
                      {n.link ? (
                        <Link to={n.link} className="text-sm text-primary hover:underline">
                          Open
                        </Link>
                      ) : null}
                    </li>
                  ))}
                </ul>
              )
            }
          </QueryBoundary>
        </Section>
      </div>
    </>
  );
}
