/**
 * Every item of the NAFDAC PSUR/PBRER Evaluation Form (V4), in order, as
 * it appears in docs/NAFDAC_PSUR_Template_V4_Proposed.docx: headings,
 * prompts, instructions, tick-box labels, and table headings and row
 * labels. Generated from the template file; v4-report.test.ts checks
 * the V4 report prints every one, so nothing on the form is left out.
 */
export const V4_TEMPLATE_ITEMS: string[] = [
  "PSUR/PBRER EVALUATION FORM",
  "National Agency for Food and Drug Administration and Control (NAFDAC)",
  "Pharmacovigilance Directorate — Structured Benefit-Risk Assessment Template (V4, Draft)",
  "Instructions: complete every section. Where a section is genuinely not applicable, write ‘Not applicable’ and state why, rather than leaving it blank. Free-text fields should give a reasoned assessment, not a single-word answer.",
  "Administrative Completeness Check",
  "Complete before starting the scientific review. A deficient submission should be returned to the MAH before detailed assessment begins.",
  "Check",
  "Yes / No / N/A",
  "Comment",
  "Does the submission follow the NAFDAC/ICH E2C(R2) recommended template",
  "Is the reporting interval / Data Lock Point (DLP) correctly stated/calculated",
  "Are all mandatory ICH E2C(R2) sections present, or is their absence explicitly justified?",
  "Was the submission received within the required regulatory timeframe?",
  "1. Product & Regulatory Information",
  "Date of Review",
  "Name of Product / Strength / Dosage Form",
  "Marketing Authorisation Holder (MAH)",
  "NAFDAC Registration Number",
  "Reporting Period",
  "International Birth Date (IBD)",
  "Nigerian Birth Date (NBD)",
  "Therapeutic Indication(s)",
  "2. Worldwide Regulatory & Marketing Status",
  "Summarise regulatory actions taken by any authority or the MAH for safety reasons this interval, worldwide (approvals, refusals, suspensions, withdrawals, variations):",
  "Any action inconsistent with, or not yet reflected in, NAFDAC's current position on this product?",
  "If yes, explain:",
  "3. Therapeutic Context",
  "Incidence and prevalence of disease:",
  "Disease duration (acute / chronic / progressive):",
  "Mortality and severity of the disease:",
  "Disease",
  "Mortality",
  "Severity",
  "Current treatment options:",
  "Quality-of-life impact of the disease/condition given current treatment options:",
  "4. Reference Safety Information (RSI)",
  "RSI type (SmPC / CDS / CCDS) and version number:",
  "Changes made to the RSI during this reporting interval:",
  "Rationale for the changes (if any):",
  "5. Exposure & Actions Taken for Safety Reasons",
  "Reporting Interval",
  "Cumulative",
  "Global exposure",
  "Nigerian exposure",
  "Another relevant region (if applicable)",
  "Provide patient years, number of patients, prescriptions, units sold, and defined daily doses, if available.",
  "Actions taken for safety reasons during the reporting interval:",
  "6. Literature",
  "Briefly highlight studies containing relevant safety information (company-sponsored and published studies):",
  "7. Aggregate Safety Data Summary",
  "Attach or reproduce the MAH's summary tabulation of ADRs and identify any SOCs requiring specific regulatory assessment (add more rows to table below as required)",
  "SOC / Event",
  "Reporting interval",
  "Cumulative",
  "Nigerian cases",
  "Reviewer assessment",
  "Note any differences between Nigeria-specific and global data, if relevant:",
  "Check VigiFlow for the Nigerian component of the product's safety data. Document the number of ICSRs received during the reporting interval and cumulatively, including the number of serious cases. Where relevant, compare the VigiFlow data with the Nigerian cases reported by the MAH and document any discrepancies.",
  "8. Signal Evaluation Log",
  "List every signal that was new, ongoing, or closed during this reporting interval. This section should not be left blank; state ‘No signals under evaluation this interval’ if genuinely applicable.",
  "Signal / Term",
  "Source",
  "Status (New/Ongoing/Closed)",
  "Method of Evaluation",
  "Outcome",
  "Date Closed",
  "Regulatory action",
  "9. Special Populations, Special Situations & Missing Information",
  "Population / Category",
  "Data Adequacy",
  "Comments",
  "Pregnancy & lactation",
  "Paediatric population",
  "Geriatric population",
  "Hepatic impairment",
  "Renal impairment",
  "Overdose / misuse / abuse potential/medication error",
  "Off-label use",
  "Other missing information",
  "10. Benefit-Risk Assessment",
  "10.1 Key Benefits",
  "Key Benefit",
  "Evidence Source",
  "Magnitude",
  "Evidence Quality (High/Moderate/Low/Very Low)",
  "10.2 Key Risks",
  "Important identified risks:",
  "Important Identified Risk",
  "Severity",
  "Frequency",
  "Reversibility",
  "Duration",
  "Preventability/Risk Management",
  "Comment",
  "Important potential risks:",
  "Important Potential Risk",
  "Severity",
  "Frequency",
  "Reversibility",
  "Duration",
  "Preventability/Risk Management",
  "Comment",
  "Frequency: state the available frequency estimate using an appropriate denominator or category, where applicable, and indicate the data source e.g RSI, SmPC, PSUR document, etc.",
  "Missing information:",
  "Missing Information",
  "Risk-Minimisation Implication",
  "10.3 Integrated Benefit-Risk Effects Table",
  "Synthesise the evidence and uncertainty for each dimension before reaching an overall conclusion (structured benefit-risk framework, modelled on the FDA five-dimension framework and CIOMS Working Group XII's Structured Benefit-Risk Framework).",
  "Dimension",
  "Evidence & Uncertainty",
  "Reviewer Conclusion",
  "Analysis of Condition / Unmet Medical Need",
  "Current Treatment Options",
  "Benefit",
  "Risk",
  "Risk Management",
  "10.4 Patient / Healthcare-Professional Perspective (If available)",
  "Where available, summarise patient- or HCP-reported views on the acceptability of the risks relative to the benefits (e.g. from PROs, patient support programmes, HCP feedback):",
  "10.5 Risk Minimisation Measures — Effectiveness This Interval (If applicable)",
  "Not applicable",
  "Effective",
  "Partially effective",
  "Not effective",
  "Not assessable — insufficient data",
  "Comment:",
  "11. Uncertainties Affecting the Benefit-Risk Assessment",
  "Data limitations or under-reporting",
  "Limited data on local (Nigerian) exposure",
  "Missing subpopulation data",
  "Short follow-up duration",
  "Study design limitations (e.g. comparator choice, randomisation, blinding)",
  "Limited generalisability of the studied population to the target population",
  "Potential impact of the uncertainty on the benefit–risk conclusion: Low / Moderate / High",
  "Other (specify)",
  "Was the uncertainty satisfactorily addressed by the MAH?",
  "Yes",
  "Partially",
  "No",
  "Rationale (mandatory — tie your answer to the specific uncertainties ticked above):",
  "Evaluator's comments (critically assess the MAH's benefit-risk profile):",
  "12. Regulatory Decision & Recommended Actions",
  "Risk Minimisation Considerations (tick all that apply)",
  "No action required",
  "Continue routine pharmacovigilance",
  "Request additional information from MAH",
  "Request MAH clarification",
  "Targeted communication / safety letter",
  "Submit or update Risk Management Plan (RMP)",
  "Proposal for Post-Authorisation Safety Study (PASS)",
  "Update to SmPC / PIL / label (variation)",
  "Refer to Expert Advisory Committee",
  "Recommend suspension/withdrawal",
  "Overall Benefit-Risk Outcome (tick one)",
  "Favourable",
  "Favourable with conditions",
  "Uncertain — requires follow-up",
  "Unfavourable",
  "Regulatory action recommended and basis for recommendation above:",
  "Specific safety/benefit–risk finding supporting the recommendation:",
  "Next PSUR/PBRER due date:",
  "Follow-up information required/follow-up deadline:",
  "13. Conclusion, Sign-off & Document Control",
  "Conclusion (state the overall benefit-risk conclusion for the product, referencing the outcome selected in Section 12 and the key drivers identified in Section 10):",
  "Reviewer confidence in this conclusion:",
  "High : robust literature review, exposure and safety data",
  "Medium: some important uncertainties",
  "Low: substantial missing information/limited or no exposure",
  "References:",
  "Evaluator's name and signature:",
  "Date:",
  "Peer reviewed by (name and signature):",
  "Date:",
];
