/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppDrugsRouteImport } from './routes/_app/drugs'
import { Route as AppE2bRouteImport } from './routes/_app/e2b'
import { Route as AppFollowUpsRouteImport } from './routes/_app/follow-ups'
import { Route as AppLineListRouteImport } from './routes/_app/line-list'
import { Route as AppLiteratureRouteImport } from './routes/_app/literature'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppOversightRouteImport } from './routes/_app/oversight'
import { Route as AppPsurRouteImport } from './routes/_app/psur'
import { Route as AppSignalsRouteImport } from './routes/_app/signals'
import { Route as AppWhatsappIntakeRouteImport } from './routes/_app/whatsapp-intake'
import { Route as AppCasesIndexRouteImport } from './routes/_app/cases.index'
import { Route as AppCasesCaseIdRouteImport } from './routes/_app/cases.$caseId'
import { Route as AppIcsrNewRouteImport } from './routes/_app/icsr.new'
import { Route as AppIntakeIndexRouteImport } from './routes/_app/intake.index'
import { Route as AppIntakeConversationIdRouteImport } from './routes/_app/intake.$conversationId'
import { Route as ROrgSlugIndexRouteImport } from './routes/r.$orgSlug.index'
import { Route as ROrgSlugReportRouteImport } from './routes/r.$orgSlug.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDrugsRoute = AppDrugsRouteImport.update({
  id: '/drugs',
  path: '/drugs',
  getParentRoute: () => AppRoute,
} as any)
const AppE2bRoute = AppE2bRouteImport.update({
  id: '/e2b',
  path: '/e2b',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpsRoute = AppFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppLineListRoute = AppLineListRouteImport.update({
  id: '/line-list',
  path: '/line-list',
  getParentRoute: () => AppRoute,
} as any)
const AppLiteratureRoute = AppLiteratureRouteImport.update({
  id: '/literature',
  path: '/literature',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppOversightRoute = AppOversightRouteImport.update({
  id: '/oversight',
  path: '/oversight',
  getParentRoute: () => AppRoute,
} as any)
const AppPsurRoute = AppPsurRouteImport.update({
  id: '/psur',
  path: '/psur',
  getParentRoute: () => AppRoute,
} as any)
const AppSignalsRoute = AppSignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => AppRoute,
} as any)
const AppWhatsappIntakeRoute = AppWhatsappIntakeRouteImport.update({
  id: '/whatsapp-intake',
  path: '/whatsapp-intake',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesIndexRoute = AppCasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesCaseIdRoute = AppCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => AppRoute,
} as any)
const AppIcsrNewRoute = AppIcsrNewRouteImport.update({
  id: '/icsr/new',
  path: '/icsr/new',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeIndexRoute = AppIntakeIndexRouteImport.update({
  id: '/intake/',
  path: '/intake/',
  getParentRoute: () => AppRoute,
} as any)
const AppIntakeConversationIdRoute = AppIntakeConversationIdRouteImport.update({
  id: '/intake/$conversationId',
  path: '/intake/$conversationId',
  getParentRoute: () => AppRoute,
} as any)
const ROrgSlugIndexRoute = ROrgSlugIndexRouteImport.update({
  id: '/r/$orgSlug/',
  path: '/r/$orgSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ROrgSlugReportRoute = ROrgSlugReportRouteImport.update({
  id: '/r/$orgSlug/report',
  path: '/r/$orgSlug/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/drugs': typeof AppDrugsRoute
  '/e2b': typeof AppE2bRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/line-list': typeof AppLineListRoute
  '/literature': typeof AppLiteratureRoute
  '/notifications': typeof AppNotificationsRoute
  '/oversight': typeof AppOversightRoute
  '/psur': typeof AppPsurRoute
  '/signals': typeof AppSignalsRoute
  '/whatsapp-intake': typeof AppWhatsappIntakeRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/icsr/new': typeof AppIcsrNewRoute
  '/intake/$conversationId': typeof AppIntakeConversationIdRoute
  '/r/$orgSlug/report': typeof ROrgSlugReportRoute
  '/cases/': typeof AppCasesIndexRoute
  '/intake/': typeof AppIntakeIndexRoute
  '/r/$orgSlug/': typeof ROrgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/audit': typeof AppAuditRoute
  '/dashboard': typeof AppDashboardRoute
  '/drugs': typeof AppDrugsRoute
  '/e2b': typeof AppE2bRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/line-list': typeof AppLineListRoute
  '/literature': typeof AppLiteratureRoute
  '/notifications': typeof AppNotificationsRoute
  '/oversight': typeof AppOversightRoute
  '/psur': typeof AppPsurRoute
  '/signals': typeof AppSignalsRoute
  '/whatsapp-intake': typeof AppWhatsappIntakeRoute
  '/cases/$caseId': typeof AppCasesCaseIdRoute
  '/icsr/new': typeof AppIcsrNewRoute
  '/intake/$conversationId': typeof AppIntakeConversationIdRoute
  '/r/$orgSlug/report': typeof ROrgSlugReportRoute
  '/cases': typeof AppCasesIndexRoute
  '/intake': typeof AppIntakeIndexRoute
  '/r/$orgSlug': typeof ROrgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/signup': typeof SignupRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/drugs': typeof AppDrugsRoute
  '/_app/e2b': typeof AppE2bRoute
  '/_app/follow-ups': typeof AppFollowUpsRoute
  '/_app/line-list': typeof AppLineListRoute
  '/_app/literature': typeof AppLiteratureRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/oversight': typeof AppOversightRoute
  '/_app/psur': typeof AppPsurRoute
  '/_app/signals': typeof AppSignalsRoute
  '/_app/whatsapp-intake': typeof AppWhatsappIntakeRoute
  '/_app/cases/$caseId': typeof AppCasesCaseIdRoute
  '/_app/icsr/new': typeof AppIcsrNewRoute
  '/_app/intake/$conversationId': typeof AppIntakeConversationIdRoute
  '/r/$orgSlug/report': typeof ROrgSlugReportRoute
  '/_app/cases/': typeof AppCasesIndexRoute
  '/_app/intake/': typeof AppIntakeIndexRoute
  '/r/$orgSlug/': typeof ROrgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/signup'
    | '/audit'
    | '/dashboard'
    | '/drugs'
    | '/e2b'
    | '/follow-ups'
    | '/line-list'
    | '/literature'
    | '/notifications'
    | '/oversight'
    | '/psur'
    | '/signals'
    | '/whatsapp-intake'
    | '/cases/$caseId'
    | '/icsr/new'
    | '/intake/$conversationId'
    | '/r/$orgSlug/report'
    | '/cases/'
    | '/intake/'
    | '/r/$orgSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/signup'
    | '/audit'
    | '/dashboard'
    | '/drugs'
    | '/e2b'
    | '/follow-ups'
    | '/line-list'
    | '/literature'
    | '/notifications'
    | '/oversight'
    | '/psur'
    | '/signals'
    | '/whatsapp-intake'
    | '/cases/$caseId'
    | '/icsr/new'
    | '/intake/$conversationId'
    | '/r/$orgSlug/report'
    | '/cases'
    | '/intake'
    | '/r/$orgSlug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/signup'
    | '/_app/audit'
    | '/_app/dashboard'
    | '/_app/drugs'
    | '/_app/e2b'
    | '/_app/follow-ups'
    | '/_app/line-list'
    | '/_app/literature'
    | '/_app/notifications'
    | '/_app/oversight'
    | '/_app/psur'
    | '/_app/signals'
    | '/_app/whatsapp-intake'
    | '/_app/cases/$caseId'
    | '/_app/icsr/new'
    | '/_app/intake/$conversationId'
    | '/r/$orgSlug/report'
    | '/_app/cases/'
    | '/_app/intake/'
    | '/r/$orgSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SignupRoute: typeof SignupRoute
  ROrgSlugReportRoute: typeof ROrgSlugReportRoute
  ROrgSlugIndexRoute: typeof ROrgSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drugs': {
      id: '/_app/drugs'
      path: '/drugs'
      fullPath: '/drugs'
      preLoaderRoute: typeof AppDrugsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/e2b': {
      id: '/_app/e2b'
      path: '/e2b'
      fullPath: '/e2b'
      preLoaderRoute: typeof AppE2bRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follow-ups': {
      id: '/_app/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AppFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/line-list': {
      id: '/_app/line-list'
      path: '/line-list'
      fullPath: '/line-list'
      preLoaderRoute: typeof AppLineListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/literature': {
      id: '/_app/literature'
      path: '/literature'
      fullPath: '/literature'
      preLoaderRoute: typeof AppLiteratureRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oversight': {
      id: '/_app/oversight'
      path: '/oversight'
      fullPath: '/oversight'
      preLoaderRoute: typeof AppOversightRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/psur': {
      id: '/_app/psur'
      path: '/psur'
      fullPath: '/psur'
      preLoaderRoute: typeof AppPsurRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/signals': {
      id: '/_app/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof AppSignalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/whatsapp-intake': {
      id: '/_app/whatsapp-intake'
      path: '/whatsapp-intake'
      fullPath: '/whatsapp-intake'
      preLoaderRoute: typeof AppWhatsappIntakeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/': {
      id: '/_app/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof AppCasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases/$caseId': {
      id: '/_app/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AppCasesCaseIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/icsr/new': {
      id: '/_app/icsr/new'
      path: '/icsr/new'
      fullPath: '/icsr/new'
      preLoaderRoute: typeof AppIcsrNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake/': {
      id: '/_app/intake/'
      path: '/intake'
      fullPath: '/intake/'
      preLoaderRoute: typeof AppIntakeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intake/$conversationId': {
      id: '/_app/intake/$conversationId'
      path: '/intake/$conversationId'
      fullPath: '/intake/$conversationId'
      preLoaderRoute: typeof AppIntakeConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/r/$orgSlug/': {
      id: '/r/$orgSlug/'
      path: '/r/$orgSlug'
      fullPath: '/r/$orgSlug/'
      preLoaderRoute: typeof ROrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$orgSlug/report': {
      id: '/r/$orgSlug/report'
      path: '/r/$orgSlug/report'
      fullPath: '/r/$orgSlug/report'
      preLoaderRoute: typeof ROrgSlugReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDrugsRoute: typeof AppDrugsRoute
  AppE2bRoute: typeof AppE2bRoute
  AppFollowUpsRoute: typeof AppFollowUpsRoute
  AppLineListRoute: typeof AppLineListRoute
  AppLiteratureRoute: typeof AppLiteratureRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOversightRoute: typeof AppOversightRoute
  AppPsurRoute: typeof AppPsurRoute
  AppSignalsRoute: typeof AppSignalsRoute
  AppWhatsappIntakeRoute: typeof AppWhatsappIntakeRoute
  AppCasesCaseIdRoute: typeof AppCasesCaseIdRoute
  AppIcsrNewRoute: typeof AppIcsrNewRoute
  AppIntakeConversationIdRoute: typeof AppIntakeConversationIdRoute
  AppCasesIndexRoute: typeof AppCasesIndexRoute
  AppIntakeIndexRoute: typeof AppIntakeIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDrugsRoute: AppDrugsRoute,
  AppE2bRoute: AppE2bRoute,
  AppFollowUpsRoute: AppFollowUpsRoute,
  AppLineListRoute: AppLineListRoute,
  AppLiteratureRoute: AppLiteratureRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOversightRoute: AppOversightRoute,
  AppPsurRoute: AppPsurRoute,
  AppSignalsRoute: AppSignalsRoute,
  AppWhatsappIntakeRoute: AppWhatsappIntakeRoute,
  AppCasesCaseIdRoute: AppCasesCaseIdRoute,
  AppIcsrNewRoute: AppIcsrNewRoute,
  AppIntakeConversationIdRoute: AppIntakeConversationIdRoute,
  AppCasesIndexRoute: AppCasesIndexRoute,
  AppIntakeIndexRoute: AppIntakeIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SignupRoute: SignupRoute,
  ROrgSlugReportRoute: ROrgSlugReportRoute,
  ROrgSlugIndexRoute: ROrgSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
